#cloud-config

# boot commands
bootcmd:
- sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
- sudo setenforce 0

# update repos
repo_update: true
repo_upgrade: all

# update packages
package_upgrade: true
packages:
  - epel-release
  - wget
  - curl 
  - policycoreutils-python 
  - perl
  - firewalld

# run commands
runcmd:
  - sudo hostnamectl set-hostname gitlab
  - sudo systemctl enable --now firewalld
  - sudo firewall-cmd --zone=public --permanent --add-port={22/tcp,80/tcp,443/tcp}
  - sudo firewall-cmd --zone=public --permanent --add-service=https
  - sudo firewall-cmd --zone=public --permanent --add-service=http
  - curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
  - sudo yum install -y gitlab-ce
  - sudo firewall-cmd --reload
  - sudo systemctl daemon-reload
  - sudo setsebool -P httpd_can_network_connect 1
  - sudo gitlab-ctl reconfigure