#cloud-config
# boot commands
bootcmd:
- sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
- setenforce 0
# update repos
repo_update: true
repo_upgrade: all
# update packages
package_upgrade: true
packages:
- epel-release
- wget
- certbot
- python2-certbot-nginx
- curl 
- policycoreutils-python 
- perl
# run commands
runcmd:
- /usr/bin/firewall-offline-cmd --add-port=22/tcp
- sudo hostnamectl set-hostname gitlab
- curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash 
- sudo EXTERNAL_URL="https://gitlab.nazydaisy.com" yum install -y gitlab-ce
- sudo firewall-cmd --zone=public --permanent --add-port={80/tcp,443/tcp}
- sudo firewall-cmd --zone=public --permanent --add-service=https
- sudo firewall-cmd --zone=public --permanent --add-service=http
- sudo firewall-cmd --reload
- sudo systemctl daemon-reload
- sudo setsebool -P httpd_can_network_connect 1
- sudo echo "nginx['custom_gitlab_server_config'] = \"location /.well-known/acme-challenge/ {\\n root /var/opt/gitlab/nginx/www/; \\n}\\n\"" >> /etc/gitlab/gitlab.rb
- sudo gitlab-ctl renew-le-certs
- sudo gitlab-ctl reconfigure